name: CI/CD för SecureWebApp

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installera .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Checka ut detta repo
        uses: actions/checkout@v4

      - name: Återställ beroenden (installera NuGet-paket)
        run: dotnet restore

      - name: Bygg och publicera appen
        run: |
          dotnet build --no-restore
          dotnet publish -c Release -o ./publish

      - name: Ladda upp app-artifacts till GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: ./publish

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download the artifacts from Github (from the build job)
        uses: actions/download-artifact@v4
        with:
          name: app-artifacts

      - name: Stop the application service
        run: |
          sudo systemctl stop SecureWebApp.service

      - name: Deploy the the application
        run: |
          sudo rm -Rf /opt/SecureWebApp || true
          sudo cp -r /home/azureuser/actions-runner/_work/SecureWebApp/SecureWebApp/ /opt/SecureWebApp

      - name: Start the application service
        run: |
          sudo systemctl start SecureWebApp.service
